### ISSUE TITLE
team check dont work 

### ISSUE THREAD

**Issue by NarimantasG** [Exunys/Aimbot-V2#14]
Game [NEW HELI] Base Battles
https://www.roblox.com/games/5326405001/NEW-HELI-Base-Battles

**Comment by Exunys** [comment]
Hello, thank you for reaching out, however, the problem is not a bug or an unintentional logical mistake. The aimbot script works fine and by the nature of the source it won't detect any pseudo characters or teams that are created by the developer/s of the game alone. This game has teams that aren't reachable by `.Team` or `.TeamColor` which is what every universal script uses (including Aimbot V2).

You can however find the teams and modify the [Raw Main.lua](https://github.com/Exunys/Aimbot-V2/blob/main/Resources/Scripts/Raw%20Main.lua) source to fit your needs, by looking in the garbage collection with `getgc()` or simply just a good look with Dark Dex will get you the resources you need.

![image](https://user-images.githubusercontent.com/76539058/216702976-dba90629-a847-4681-b59a-60a36a8e340e.png)
![image](https://user-images.githubusercontent.com/76539058/216702983-bae02a02-2863-4578-bfb0-ee0de6263a1d.png)
