### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by DeliFreshRoblox** [Exunys/Aimbot-V2#6]
How would I implement this into a personal GUI? I would just have on, off, and reset settings buttons.

**Comment by Exunys** [comment]
> How would I implement this into a personal GUI? I would just have on, off, and reset settings buttons. 

Hello, by reading the environment table and its structure you will get all the answers you need, also it is recommended that you use Raw Main.lua because it allows for a better workplace for if you are implementing the script somewhere else. Here are some examples:

First of all, you will need to load the (raw) aimbot's environment into the script, by reading README.md > Script (paste the loadstring of the bullet that says Raw Main.lua at the top of your code and upon execution the getgenv().Aimbot environment will load).

Reset Settings (Button)

```lua
EVENT(function()
  getgenv().Aimbot.Functions:ResetSettings()
end)

-- You will also need to reset the GUI values / configurations to match with the default / new values.
```

FOV (Slider)

```lua
EVENT(function(FOV_ARG)
   getgenv().Aimbot.FOVSettings.Amount = FOV_ARG
end)
```

FOV Visual Color (RGB Color Picker)

```lua
EVENT(function(R, G, B)
   getgenv().Aimbot.FOVSettings.Color = Color3.fromRGB(R, G, B) -- <Color3> and not <string> because Raw Main.lua doesn't use Exunys Developer storing systems.
end)
```

These are some of the options & configurations, the other ones should be pretty much the same.

That should be pretty much all you need to implement this script into a GUI / UI Library.

Please make sure to credit me incase you do reuse my code (read LICENSE).
